package util

const ApiPattern = "/api"
const RootPattern = "/"
const V1 = "/v1"
const UsersPattern = "/users"
const ContentsPattern = "/contents"
const ContextKey = "userId"
const UrlKeyId = "id"
const UrlKeyLastId = "lastId"
const RowsAffected = "rowsAffected"
const InternalServerError = "internal server error"
const NotFound = "not found"
const BadRequest = "bad request"
const Error = "error"
