version: "3.9"
services:
  rest-api-starter-go:
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
    image: rest-api-starter-go
    container_name: rest-api-starter-go
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    container_name: mongo
    volumes:
      - starter-data:/var/lib/mongo/data
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=starterDB
volumes:
  starter-data:
